#!/usr/bin/env python3
"""Package editors/vscode as a VS Code extension (.vsix) without Node.js or vsce.

A .vsix is an Open Packaging Conventions zip. This script writes the same
layout `vsce package` produces for a declarative (grammar-only) extension:

    dist/rivet-<version>.vsix
    ├── [Content_Types].xml          default content type per file extension
    ├── extension.vsixmanifest       identity (publisher.name@version), engine, assets
    └── extension/
        ├── package.json             the extension manifest (contributes languages + grammars)
        ├── README.md                shown as the extension's details page
        ├── language-configuration.json
        └── syntaxes/rivet.tmLanguage.json   (generated by editors/gen_grammar.py)

Files matched by editors/vscode/.vscodeignore are left out. The archive is
deterministic (sorted entries, fixed timestamps), so the same sources always
give the same bytes and SHA-256.

    python3 editors/vscode/package_vsix.py [--out DIR]     # default DIR: <repo>/dist
    code --install-extension dist/rivet-0.1.0.vsix

The package.json version must equal the Cargo.toml workspace (else package) version (checked
here and by `cargo test --test conformance_highlight`).
Standard library only.
"""

from __future__ import annotations

import fnmatch
import json
import re
import sys
import zipfile
from pathlib import Path
from xml.sax.saxutils import escape

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
FIXED_TIME = (1980, 1, 1, 0, 0, 0)

CONTENT_TYPES = {
    ".json": "application/json",
    ".md": "text/markdown",
    ".txt": "text/plain",
    ".png": "image/png",
    ".vsixmanifest": "text/xml",
}


def cargo_version() -> str:
    text = (ROOT / "Cargo.toml").read_text(encoding="utf-8")
    # The workspace version (PLAN-2026-0002 TASK-030) is the one version source;
    # a manifest without a workspace keeps [package].version.
    m = re.search(r'^\[workspace\.package\][^\[]*?^version\s*=\s*"([^"]+)"', text, re.S | re.M) or re.search(
        r'^\[package\][^\[]*?^version\s*=\s*"([^"]+)"', text, re.S | re.M
    )
    if not m:
        raise SystemExit("package_vsix: no [package] version in Cargo.toml")
    return m.group(1)


def ignored(rel: str, patterns: list[str]) -> bool:
    for p in patterns:
        if fnmatch.fnmatch(rel, p) or fnmatch.fnmatch(Path(rel).name, p):
            return True
        if p.endswith("/**") and (rel + "/").startswith(p[:-2]):
            return True
        if p.startswith("**/") and fnmatch.fnmatch(Path(rel).name, p[3:]):
            return True
    return False


def extension_files() -> list[tuple[str, Path]]:
    ignore_file = HERE / ".vscodeignore"
    patterns = [
        line.strip()
        for line in ignore_file.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]
    files = []
    for path in sorted(HERE.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(HERE).as_posix()
        if ignored(rel, patterns):
            continue
        files.append((rel, path))
    return files


def manifest(pkg: dict) -> str:
    engine = pkg.get("engines", {}).get("vscode", "*")
    tags = sorted(set(pkg.get("keywords", [])) | {f"__ext_{e.lstrip('.')}" for lang in pkg["contributes"]["languages"] for e in lang.get("extensions", [])})
    categories = ",".join(pkg.get("categories", []))
    repo = pkg.get("repository", {}).get("url", "")
    props = [
        ("Microsoft.VisualStudio.Code.Engine", engine),
        ("Microsoft.VisualStudio.Code.ExtensionDependencies", ""),
        ("Microsoft.VisualStudio.Code.ExtensionPack", ""),
        ("Microsoft.VisualStudio.Code.ExtensionKind", "workspace"),
        ("Microsoft.VisualStudio.Code.LocalizedLanguages", ""),
        ("Microsoft.VisualStudio.Services.Links.Source", repo),
        ("Microsoft.VisualStudio.Services.GitHubFlavoredMarkdown", "true"),
        ("Microsoft.VisualStudio.Services.Content.Pricing", "Free"),
    ]
    prop_xml = "\n      ".join(
        f'<Property Id="{escape(k)}" Value="{escape(v)}" />' for k, v in props
    )
    return f"""<?xml version="1.0" encoding="utf-8"?>
<PackageManifest Version="2.0.0" xmlns="http://schemas.microsoft.com/developer/vsx-schema/2011" xmlns:d="http://schemas.microsoft.com/developer/vsx-schema-design/2011">
  <Metadata>
    <Identity Language="en-US" Id="{escape(pkg['name'])}" Version="{escape(pkg['version'])}" Publisher="{escape(pkg['publisher'])}" />
    <DisplayName>{escape(pkg.get('displayName', pkg['name']))}</DisplayName>
    <Description xml:space="preserve">{escape(pkg.get('description', ''))}</Description>
    <Tags>{escape(','.join(tags))}</Tags>
    <Categories>{escape(categories)}</Categories>
    <GalleryFlags>Public</GalleryFlags>
    <Properties>
      {prop_xml}
    </Properties>
    <License>extension/README.md</License>
  </Metadata>
  <Installation>
    <InstallationTarget Id="Microsoft.VisualStudio.Code" />
  </Installation>
  <Dependencies />
  <Assets>
    <Asset Type="Microsoft.VisualStudio.Code.Manifest" Path="extension/package.json" Addressable="true" />
    <Asset Type="Microsoft.VisualStudio.Services.Content.Details" Path="extension/README.md" Addressable="true" />
  </Assets>
</PackageManifest>
"""


def content_types(names: list[str]) -> str:
    exts = sorted({Path(n).suffix for n in names if Path(n).suffix} | {".vsixmanifest"})
    defaults = "".join(
        f'<Default Extension="{escape(e)}" ContentType="{CONTENT_TYPES.get(e, "application/octet-stream")}" />'
        for e in exts
    )
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">{defaults}</Types>\n'
    )


def write_entry(zf: zipfile.ZipFile, name: str, data: bytes):
    info = zipfile.ZipInfo(name, date_time=FIXED_TIME)
    info.compress_type = zipfile.ZIP_DEFLATED
    info.external_attr = 0o644 << 16
    zf.writestr(info, data)


def main(argv: list[str]) -> int:
    out_dir = ROOT / "dist"
    if "--out" in argv:
        out_dir = Path(argv[argv.index("--out") + 1]).resolve()
    pkg = json.loads((HERE / "package.json").read_text(encoding="utf-8"))
    version = cargo_version()
    if pkg["version"] != version:
        print(
            f"package_vsix: editors/vscode/package.json version {pkg['version']} != Cargo.toml {version}",
            file=sys.stderr,
        )
        return 1
    files = extension_files()
    rels = [r for r, _ in files]
    for required in ("package.json", "README.md", "language-configuration.json", "syntaxes/rivet.tmLanguage.json"):
        if required not in rels:
            print(f"package_vsix: editors/vscode/{required} is missing", file=sys.stderr)
            return 1
    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / f"{pkg['name']}-{pkg['version']}.vsix"
    names = [f"extension/{r}" for r in rels]
    with zipfile.ZipFile(target, "w") as zf:
        write_entry(zf, "[Content_Types].xml", content_types(names).encode("utf-8"))
        write_entry(zf, "extension.vsixmanifest", manifest(pkg).encode("utf-8"))
        for rel, path in files:
            write_entry(zf, f"extension/{rel}", path.read_bytes())
    print(f"package_vsix: wrote {target} ({len(files)} extension files)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
