/*
 * rivet.h — the C ABI of Rivet (librivet), ABI version 1.
 *
 * JSON in, JSON out, over NUL-terminated UTF-8 strings.
 *   - Every `char *` returned (except rivet_version()) is owned by the caller:
 *     free it with rivet_string_free().
 *   - Errors are ResponseEnvelope JSON with "status":"error" (never a crash):
 *     NULL / non-UTF-8 / freed arguments are validation.ffi_argument, panics
 *     are internal.panic.
 *   - RivetRuntime and RivetModule are thread-safe; a RivetCall belongs to one
 *     thread at a time. Handles are opaque; a freed handle is refused.
 *
 *   rivet_runtime_new(opts, &rt, &err) ─▶ rivet_request(rt, input) ─▶ envelope
 *   rivet_call_start(rt, input) ─▶ rivet_call_next(call, ms) … NULL ─▶ rivet_call_free
 *   rivet_load(rt, path, alias, &module, &err) ─▶ rivet_module_call(module, id, data)
 */

#ifndef RIVET_H
#define RIVET_H

/* Generated by cbindgen from ffi/src/lib.rs (rivet-ffi); do not edit by hand. */

#include <stdint.h>

// Result of the functions that also hand back a handle or an error envelope.
typedef enum RivetStatus {
  RIVET_OK = 0,
  RIVET_ERROR = 1,
} RivetStatus;

// One running call: pull its records with `rivet_call_next` (one thread at a time).
typedef struct RivetCall RivetCall;

// A `.rivet` file loaded into a runtime as an object of operations (thread-safe).
typedef struct RivetModule RivetModule;

// A loaded bundle and the async runtime that drives it (thread-safe).
typedef struct RivetRuntime RivetRuntime;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// The ABI major version (1). Bumped only on a breaking change to rivet.h.
uint32_t rivet_abi_version(void);

// The library version ("0.2.0"); a static string, do not free.
const char *rivet_version(void);

// Build a runtime from `options_json` (`{file | source+path+root | root,
// policy_file | policy_json, ceiling_json?, pretty?}`). On success `*out` is the
// handle and RIVET_OK is returned; otherwise `*error_json` (if not NULL) is an
// error envelope to free with `rivet_string_free`.
enum RivetStatus rivet_runtime_new(const char *options_json,
                                   struct RivetRuntime **out_rt,
                                   char **error_json);

// Cancel and drain in-flight calls (5 s grace), then free the runtime.
// RIVET_ERROR for NULL, a foreign or an already freed handle.
enum RivetStatus rivet_runtime_free(struct RivetRuntime *rt);

// Blocking call from an input envelope (`{operation, data, deadline_ms?,
// restrict?, pretty?}`); always returns a ResponseEnvelope.
char *rivet_request(struct RivetRuntime *rt, const char *input_json);

// Start a call (streams and live input included). Never NULL: a failed start
// yields its error record on the first `rivet_call_next`.
struct RivetCall *rivet_call_start(struct RivetRuntime *rt, const char *input_json);

// The next record (`type: data` … then `type: result`), `{"type":"timeout"}`
// when nothing arrived within `timeout_ms` (negative waits), NULL when done.
char *rivet_call_next(struct RivetCall *call, int64_t timeout_ms);

// Send one live input item (JSON); returns the ack or an error envelope.
char *rivet_call_send(struct RivetCall *call, const char *data_json);

// Close the call's live input; returns the ack or an error envelope.
char *rivet_call_finish_input(struct RivetCall *call);

// Cancel the call; its records end with `status: "cancelled"`.
enum RivetStatus rivet_call_cancel(struct RivetCall *call);

// Free the call (a running call is cancelled first, 5 s grace). A second
// free returns RIVET_ERROR.
enum RivetStatus rivet_call_free(struct RivetCall *call);

// Highlight a `.rivet` source: `format` is "json" (default when NULL),
// "html" or "ansi".
char *rivet_highlight(const char *source, const char *format);

// Load a `.rivet` file below the runtime root as a module (alias = file stem
// when `alias_or_null` is NULL). RIVET_OK and `*out`, or RIVET_ERROR and
// `*error_json`.
enum RivetStatus rivet_load(struct RivetRuntime *rt,
                            const char *path,
                            const char *alias_or_null,
                            struct RivetModule **out_module,
                            char **error_json);

// The module's operations as a JSON array of `{id, operation, name,
// description, emits, receives}` (or an error envelope).
char *rivet_module_operations(struct RivetModule *module);

// Blocking call of one module operation by its short ID (`"get"`); the
// envelope names the namespaced operation (`users.get`). NULL data = `{}`.
char *rivet_module_call(struct RivetModule *module, const char *id, const char *data_json);

// Start a call of one module operation (see `rivet_call_start`).
struct RivetCall *rivet_module_call_start(struct RivetModule *module,
                                          const char *id,
                                          const char *data_json);

// Free the module handle; the module stays loaded in its runtime.
enum RivetStatus rivet_module_free(struct RivetModule *module);

// Free a string returned by librivet. NULL is a no-op (RIVET_OK); a pointer
// librivet did not return, or already freed, is refused (RIVET_ERROR).
enum RivetStatus rivet_string_free(char *s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RIVET_H */
