"""Local QUIC + HTTP/3 fixture for docs/demos/09-quic (aioquic).

    UDP 127.0.0.1:<quic-port>  ALPN rivet-rpc/1   each bidi stream: read one
                               length32 big-endian JSON frame, answer
                               {"state":"ready"} in one frame, finish the stream
    UDP 127.0.0.1:<h3-port>    ALPN h3            GET /items -> 200 {"items":[]}
                                                  anything else -> 404

Usage:
    python quic_fixture.py --cert server.pem --key server.key \
        [--quic-port 18890] [--h3-port 18891] [--rpc-silent]

Needs `pip install aioquic`. The certificate is generated by the README's
openssl commands in a scratch directory; no key material is committed.
"""

import argparse
import asyncio
import json
import struct

from aioquic.asyncio import QuicConnectionProtocol, serve
from aioquic.h3.connection import H3_ALPN, H3Connection
from aioquic.h3.events import HeadersReceived
from aioquic.quic.configuration import QuicConfiguration
from aioquic.quic.events import ProtocolNegotiated, StreamDataReceived

STATUS = json.dumps({"state": "ready"}, separators=(",", ":")).encode()
ITEMS = json.dumps({"items": []}, separators=(",", ":")).encode()


class RpcProtocol(QuicConnectionProtocol):
    """rivet-rpc/1: one length-prefixed JSON request frame per bidi stream."""

    silent = False  # --rpc-silent: read the frame, never answer (timeout demo)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._buf = {}

    def quic_event_received(self, event):
        if not isinstance(event, StreamDataReceived):
            return
        buf = self._buf.get(event.stream_id, b"") + event.data
        self._buf[event.stream_id] = buf
        if len(buf) < 4:
            return
        (size,) = struct.unpack(">I", buf[:4])
        if len(buf) < 4 + size:
            return
        request = json.loads(buf[4 : 4 + size])
        print(f"rpc stream {event.stream_id}: {request}", flush=True)
        if self.silent:
            return
        reply = STATUS if request.get("action") == "status" else b'{"error":"unknown"}'
        self._quic.send_stream_data(
            event.stream_id, struct.pack(">I", len(reply)) + reply, end_stream=True
        )
        del self._buf[event.stream_id]
        self.transmit()


class H3Protocol(QuicConnectionProtocol):
    """h3: GET /items answers {"items":[]}."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._h3 = None

    def quic_event_received(self, event):
        if isinstance(event, ProtocolNegotiated):
            self._h3 = H3Connection(self._quic)
        if self._h3 is None:
            return
        for ev in self._h3.handle_event(event):
            if isinstance(ev, HeadersReceived):
                headers = dict(ev.headers)
                method = headers.get(b":method", b"").decode()
                path = headers.get(b":path", b"").decode()
                print(f"h3 {method} {path}", flush=True)
                if method == "GET" and path == "/items":
                    status, body = b"200", ITEMS
                else:
                    status, body = b"404", b'{"error":"not found"}'
                self._h3.send_headers(
                    ev.stream_id,
                    [
                        (b":status", status),
                        (b"content-type", b"application/json"),
                        (b"content-length", str(len(body)).encode()),
                    ],
                )
                self._h3.send_data(ev.stream_id, body, end_stream=True)
        self.transmit()


def config(alpn, cert, key):
    c = QuicConfiguration(is_client=False, alpn_protocols=alpn)
    c.load_cert_chain(cert, key)
    return c


async def main():
    p = argparse.ArgumentParser()
    p.add_argument("--cert", required=True)
    p.add_argument("--key", required=True)
    p.add_argument("--host", default="127.0.0.1")
    p.add_argument("--quic-port", type=int, default=18890)
    p.add_argument("--h3-port", type=int, default=18891)
    p.add_argument("--rpc-silent", action="store_true",
                   help="accept rivet-rpc/1 frames but never reply")
    a = p.parse_args()
    RpcProtocol.silent = a.rpc_silent
    await serve(a.host, a.quic_port, configuration=config(["rivet-rpc/1"], a.cert, a.key),
                create_protocol=RpcProtocol)
    await serve(a.host, a.h3_port, configuration=config(H3_ALPN, a.cert, a.key),
                create_protocol=H3Protocol)
    print(f"quic rivet-rpc/1 on udp {a.host}:{a.quic_port}; h3 on udp {a.host}:{a.h3_port}",
          flush=True)
    await asyncio.Future()


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        pass
