//! Syntax highlighting from real parser spans (PROP-2026-0002 R17, UC-08).
//!
//! ```text
//!  SourceFile ──parser.parse──▶ SyntaxTree (statement nodes + capture spans)
//!      │                              │
//!      │        per node: leading keyword (func) · captures (id, var, name, value, cond, rest…)
//!      │                  · glue literals between captures (`in`, `after`, `=`, `map`)
//!      │                              ▼
//!      │                   lex each span ─▶ classify with editors/keywords.json
//!      │                   (the table generated from src/infra/rivet.capy)
//!      ▼
//!  gap scan (text no node covers): `#` comments, the `else` section keyword and
//!  the `end` of a flat option line's sub-block (Capy keeps no node for it)
//!      ▼
//!  syntax error? ──yes──▶ keep the tokens that start before the earliest diagnostic
//!      ▼                  + that diagnostic (syntax.*, exit 2)
//!  [HighlightToken{line, col, len, class, text}]   one line each, sorted, non-overlapping
//! ```
//!
//! Classes: keyword, option, type, effect, string, interpolation, number,
//! comment, operation_id, global, variable, operator. Brackets, commas, colons,
//! object keys and whitespace are not tokens (renderers copy them unchanged).

use crate::domain::highlight::HighlightToken;
use crate::domain::ports::Parser;
use crate::domain::source::{SourceFile, offset_of};
use crate::domain::syntax_tree::{SyntaxDiagnostic, SyntaxNode};
use crate::domain::{RivetError, RivetResult};
use std::collections::{HashMap, HashSet};
use std::sync::OnceLock;

/// The keyword table generated by `editors/gen_grammar.py` from `rivet.capy`
/// (shared with the TextMate grammar; `editors/check_keywords.py` guards drift).
const KEYWORDS_JSON: &str = include_str!("../../../editors/keywords.json");

struct Table {
    /// Capy function → its first literal (`opt_decode` → `decode`, `assign` → `=`).
    statement: HashMap<String, String>,
    /// Table class (declaration, control, option, type, effect, …) → words.
    classes: HashMap<String, HashSet<String>>,
    /// Table class → R17 highlight class.
    class_of: HashMap<String, String>,
}

impl Table {
    fn load() -> RivetResult<&'static Table> {
        static TABLE: OnceLock<Result<Table, String>> = OnceLock::new();
        TABLE
            .get_or_init(|| {
                let j: serde_json::Value =
                    serde_json::from_str(KEYWORDS_JSON).map_err(|e| e.to_string())?;
                let strings = |v: &serde_json::Value| -> HashSet<String> {
                    v.as_array()
                        .map(|a| {
                            a.iter()
                                .filter_map(|s| s.as_str().map(str::to_string))
                                .collect()
                        })
                        .unwrap_or_default()
                };
                let map = |key: &str| -> HashMap<String, String> {
                    j[key]
                        .as_object()
                        .map(|m| {
                            m.iter()
                                .filter_map(|(k, v)| Some((k.clone(), v.as_str()?.to_string())))
                                .collect()
                        })
                        .unwrap_or_default()
                };
                let classes = j["classes"]
                    .as_object()
                    .ok_or("keywords.json has no `classes`")?
                    .iter()
                    .map(|(k, v)| (k.clone(), strings(v)))
                    .collect();
                Ok(Table {
                    statement: map("statements"),
                    classes,
                    class_of: map("highlight_class_of"),
                })
            })
            .as_ref()
            .map_err(|e| RivetError::internal(format!("editors/keywords.json: {e}")))
    }

    fn is(&self, class: &str, word: &str) -> bool {
        self.classes.get(class).is_some_and(|s| s.contains(word))
    }

    /// The R17 class of a table word in statement/glue position, if any.
    fn word_class(&self, word: &str) -> Option<&str> {
        for class in [
            "declaration",
            "control",
            "boolean_null",
            "operator",
            "effect",
            "option",
            "type",
        ] {
            if self.is(class, word) {
                return self.class_of.get(class).map(String::as_str);
            }
        }
        None
    }
}

/// One raw lexeme of a span (byte range into the file text).
#[derive(Clone, Debug, PartialEq)]
enum Lex {
    /// Identifier path: `r`, `r.body`, `xs.0`, `base64.encode`.
    Word,
    Number,
    /// A string literal with its `${…}` interpolation byte ranges.
    Str(Vec<(usize, usize)>),
    Comment,
    /// Operator punctuation (`=`, `==`, `+=`, `.`, `-`, …).
    Op,
    Open(u8),
    /// `)`, `]`, `}`, `,` and `:` (never tokens).
    Punct(u8),
}

fn lex(text: &str, from: usize, to: usize) -> Vec<(Lex, usize, usize)> {
    let b = text.as_bytes();
    let to = to.min(b.len());
    let mut out = Vec::new();
    let mut i = from;
    let ident = |c: char| c.is_alphanumeric() || c == '_';
    while i < to {
        let c = text[i..].chars().next().unwrap_or(' ');
        let start = i;
        if c.is_whitespace() {
            i += c.len_utf8();
        } else if c == '#' {
            while i < to && b[i] != b'\n' {
                i += 1;
            }
            out.push((Lex::Comment, start, i));
        } else if c == '"' || c == '\'' || c == '`' {
            let q = b[i];
            let mut interp = Vec::new();
            i += 1;
            while i < to && b[i] != q {
                if b[i] == b'\\' {
                    i += 2;
                    continue;
                }
                if b[i] == b'\n' && q != b'`' {
                    break;
                }
                if b[i] == b'$' && b.get(i + 1) == Some(&b'{') {
                    let s = i;
                    while i < to && b[i] != b'}' && b[i] != q {
                        i += 1;
                    }
                    if i < to && b[i] == b'}' {
                        i += 1;
                        interp.push((s, i));
                    }
                    continue;
                }
                i += 1;
            }
            i = (i + 1).min(to);
            out.push((Lex::Str(interp), start, i));
        } else if c.is_ascii_digit() {
            while i < to && (b[i].is_ascii_digit() || b[i] == b'_') {
                i += 1;
            }
            if i + 1 < to && b[i] == b'.' && b[i + 1].is_ascii_digit() {
                i += 1;
                while i < to && b[i].is_ascii_digit() {
                    i += 1;
                }
            }
            out.push((Lex::Number, start, i));
        } else if ident(c) {
            loop {
                while i < to {
                    let ch = text[i..].chars().next().unwrap_or(' ');
                    if !ident(ch) {
                        break;
                    }
                    i += ch.len_utf8();
                }
                // `.` followed by a name or an index continues the path.
                let next = text[(i + 1).min(to)..].chars().next();
                if i + 1 < to && b[i] == b'.' && next.is_some_and(ident) {
                    i += 1;
                    continue;
                }
                break;
            }
            out.push((Lex::Word, start, i));
        } else if matches!(c, '(' | '[' | '{') {
            i += 1;
            out.push((Lex::Open(b[start]), start, i));
        } else if matches!(c, ')' | ']' | '}' | ',' | ':') {
            i += 1;
            out.push((Lex::Punct(b[start]), start, i));
        } else if "=<>!+-*/%&|^~?.;@$\\".contains(c) {
            while i < to && "=<>!+-*/%&|^~?.;@$\\".contains(b[i] as char) {
                i += 1;
            }
            out.push((Lex::Op, start, i));
        } else {
            i += c.len_utf8();
        }
    }
    out
}

/// How a span's words are read.
#[derive(Clone, Copy, PartialEq)]
enum Mode {
    /// An expression capture (`value`, `cond`, `iter`, …): names are variables or globals.
    Expr,
    /// An option tail (`rest`, `filter`): option words, types and effects are keywords too.
    Tail,
    /// Literals between captures (`in`, `after`, `=`, `map`, `poll`).
    Glue,
}

struct Tokens<'a> {
    text: &'a str,
    table: &'a Table,
    globals: HashSet<String>,
    /// (byte start, byte end, class), possibly multi-line until `finish`.
    out: Vec<(usize, usize, &'static str)>,
    /// Byte ranges the node walk covered (the rest is gap-scanned).
    covered: Vec<(usize, usize)>,
}

const CLASSES: &[&str] = crate::domain::highlight::TOKEN_CLASSES;

fn class(name: &str) -> &'static str {
    CLASSES
        .iter()
        .find(|c| **c == name)
        .copied()
        .unwrap_or("variable")
}

impl<'a> Tokens<'a> {
    fn push(&mut self, s: usize, e: usize, class_name: &str) {
        if e > s {
            self.out.push((s, e, class(class_name)));
        }
    }

    fn offset(&self, line: u32, col: u32) -> usize {
        offset_of(self.text, line, col).unwrap_or(self.text.len())
    }

    /// Lex `[from, to)` in `mode`; `effect_first` makes a leading effect word
    /// (`http`, `file`, …) and the verb after it (`get`) effects.
    fn span(&mut self, from: usize, to: usize, mode: Mode, effect_first: bool) -> bool {
        let lexemes = lex(self.text, from, to);
        let mut saw_effect = false;
        let mut first_word = true;
        for (k, (lx, s, e)) in lexemes.iter().enumerate() {
            let prev = k.checked_sub(1).map(|p| &lexemes[p].0);
            let next = lexemes.get(k + 1).map(|n| &n.0);
            match lx {
                Lex::Comment => self.push(*s, *e, "comment"),
                Lex::Number => self.push(*s, *e, "number"),
                Lex::Op => self.push(*s, *e, "operator"),
                Lex::Open(_) | Lex::Punct(_) => {}
                Lex::Str(interp) => {
                    let mut at = *s;
                    for (a, b) in interp {
                        self.push(at, *a, "string");
                        self.push(*a, *b, "interpolation");
                        at = *b;
                    }
                    self.push(at, *e, "string");
                }
                Lex::Word => {
                    let w = &self.text[*s..*e];
                    let root = w.split('.').next().unwrap_or(w);
                    let was_first = first_word;
                    first_word = false;
                    // object keys (`{id: …}`) are not tokens
                    if next == Some(&Lex::Punct(b':'))
                        && matches!(prev, Some(Lex::Open(b'{')) | Some(Lex::Punct(b',')))
                    {
                        continue;
                    }
                    let class_name = if prev == Some(&Lex::Open(b'(')) {
                        if self.table.is("builtin", w) {
                            "keyword"
                        } else {
                            "operation_id"
                        }
                    } else if self.table.is("boolean_null", w) {
                        "keyword"
                    } else if self.table.is("operator", w) {
                        "operator"
                    } else if mode == Mode::Glue {
                        self.table.word_class(w).unwrap_or("variable")
                    } else if self.globals.contains(root) {
                        "global"
                    } else if effect_first && was_first && self.table.is("effect", w) {
                        saw_effect = true;
                        "effect"
                    } else if effect_first
                        && saw_effect
                        && k == 1
                        && !w.contains('.')
                        && matches!(next, None | Some(Lex::Str(_)) | Some(Lex::Word))
                    {
                        "effect"
                    } else if mode == Mode::Tail && self.table.is("type", w) {
                        "type"
                    } else if mode == Mode::Tail
                        && (self.table.is("option", w) || w == "description")
                    {
                        "option"
                    } else if mode == Mode::Tail && self.table.is("declaration", w) {
                        "keyword"
                    } else {
                        "variable"
                    };
                    self.push(*s, *e, class_name);
                }
            }
        }
        saw_effect
    }

    fn node(&mut self, n: &SyntaxNode) {
        let start = self.offset(n.span.start_line, n.span.start_col);
        let end = self.offset(n.span.end_line, n.span.end_col).max(start);
        let block = n.body.is_some() || n.closer.is_some() || !n.sections.is_empty();
        let mut cursor = start;
        // The leading keyword: the function's first literal when the source starts with it.
        if let Some(lit) = self.table.statement.get(&n.func).cloned() {
            let rest = &self.text[start..];
            let boundary = rest[lit.len().min(rest.len())..]
                .chars()
                .next()
                .is_none_or(|c| !(c.is_alphanumeric() || c == '_'));
            if lit.chars().all(|c| c.is_ascii_alphabetic() || c == '_')
                && rest.starts_with(lit.as_str())
                && boundary
            {
                let class_name = if n.func.starts_with("opt_") {
                    "option"
                } else if self.table.is("effect", &lit) {
                    "effect"
                } else {
                    "keyword"
                };
                self.push(start, start + lit.len(), class_name);
                cursor = start + lit.len();
            }
        }
        let mut caps: Vec<(&str, usize, usize)> = n
            .captures
            .iter()
            .filter_map(|(name, c)| {
                let s = c.span.as_ref()?;
                let a = self.offset(s.start_line, s.start_col);
                let b = self.offset(s.end_line, s.end_col);
                (b > a && a >= cursor).then_some((name.as_str(), a, b))
            })
            .collect();
        caps.sort_by_key(|c| c.1);
        let func = n.func.as_str();
        let assigns = matches!(
            func,
            "assign" | "assign_block" | "append_assign" | "node" | "node_after"
        );
        let effect_stmt = matches!(func, "with" | "file" | "file_block");
        let mut value_was_effect = false;
        for (name, a, b) in caps {
            if a < cursor {
                continue;
            }
            self.span(cursor, a, Mode::Glue, false);
            match (func, name) {
                ("operation" | "pipeline", "id") => self.push(a, b, "operation_id"),
                (_, "var" | "item" | "obj" | "method") => self.push(a, b, "variable"),
                (_, "name") if func != "name" => self.push(a, b, "variable"),
                ("connector" | "auth_profile", "kind") => self.push(a, b, "type"),
                ("global", "rest") => self.global_tail(a, b),
                ("import", "rest") => {
                    self.span(a, b, Mode::Tail, false);
                }
                (_, "value") => value_was_effect = self.span(a, b, Mode::Expr, assigns),
                (_, "rest" | "filter") => {
                    if value_was_effect {
                        self.effect_verb_tail(a, b);
                    } else {
                        self.span(a, b, Mode::Tail, effect_stmt);
                    }
                }
                _ => {
                    self.span(a, b, Mode::Expr, false);
                }
            }
            cursor = b;
        }
        let header_end = if block { cursor } else { end.max(cursor) };
        if !block {
            // a statement made only of literals (`break`, `end`, `try`)
            self.span(
                cursor,
                cursor.max(header_end.min(self.line_end(cursor))),
                Mode::Glue,
                false,
            );
        }
        self.covered.push((start, header_end));
        for c in n.children() {
            self.node(c);
        }
        for (_, body) in &n.sections {
            for c in body {
                self.node(c);
            }
        }
        if let Some(c) = &n.closer {
            self.node(c);
        }
    }

    fn line_end(&self, from: usize) -> usize {
        self.text[from..]
            .find('\n')
            .map(|k| from + k)
            .unwrap_or(self.text.len())
    }

    /// `global NAME = EXPR`: NAME is a global, the rest an expression.
    fn global_tail(&mut self, a: usize, b: usize) {
        let lexemes = lex(self.text, a, b);
        if let Some((Lex::Word, s, e)) = lexemes.first() {
            self.push(*s, *e, "global");
            self.span(*e, b, Mode::Expr, false);
        } else {
            self.span(a, b, Mode::Expr, false);
        }
    }

    /// `r = http get "url" …`: the verb after the effect head is an effect.
    fn effect_verb_tail(&mut self, a: usize, b: usize) {
        let lexemes = lex(self.text, a, b);
        match lexemes.first() {
            Some((Lex::Word, s, e)) if !self.text[*s..*e].contains('.') => {
                self.push(*s, *e, "effect");
                self.span(*e, b, Mode::Tail, false);
            }
            _ => {
                self.span(a, b, Mode::Tail, false);
            }
        }
    }

    /// Text no node header covers: `#` comments, the `else` section word and
    /// block `end`s the tree does not keep. With `recover` (the tree has
    /// diagnostics), a line no node covers is a statement the parser could not
    /// keep (e.g. the header of an unclosed `operation … ⏎ … return (` block):
    /// it is lexed as a statement line so its tokens before the error still
    /// appear (INC-2026-0012 item 9).
    fn gaps(&mut self, recover: bool) {
        let mut covered = self.covered.clone();
        covered.sort();
        let mut at = 0usize;
        let mut gaps = Vec::new();
        for (s, e) in covered {
            if s > at {
                gaps.push((at, s));
            }
            at = at.max(e);
        }
        gaps.push((at, self.text.len()));
        for (s, e) in gaps {
            if recover {
                self.recover_lines(s, e);
                continue;
            }
            for (lx, a, b) in lex(self.text, s, e) {
                match lx {
                    Lex::Comment => self.push(a, b, "comment"),
                    // `else` is a section name, and the `end` of a flat option
                    // line's sub-block (`transport command …` / `end`) is not a node
                    Lex::Word if matches!(&self.text[a..b], "else" | "end") => {
                        self.push(a, b, "keyword")
                    }
                    _ => {}
                }
            }
        }
    }

    /// Lex each line of an uncovered range as a statement: a leading
    /// declaration or control word is a keyword (the ID after `operation` /
    /// `pipeline` an operation_id), the rest reads like an option tail.
    fn recover_lines(&mut self, from: usize, to: usize) {
        let mut a = from;
        while a < to {
            let e = self.line_end(a).min(to);
            let lexemes = lex(self.text, a, e);
            match lexemes.first() {
                Some((Lex::Word, s0, e0))
                    if matches!(&self.text[*s0..*e0], "end" | "else")
                        || self.table.is("declaration", &self.text[*s0..*e0])
                        || self.table.is("control", &self.text[*s0..*e0]) =>
                {
                    let head = &self.text[*s0..*e0];
                    self.push(*s0, *e0, "keyword");
                    let mut rest = *e0;
                    if matches!(head, "operation" | "pipeline")
                        && let Some((Lex::Word, s1, e1)) = lexemes.get(1)
                    {
                        self.push(*s1, *e1, "operation_id");
                        rest = *e1;
                    }
                    self.span(rest, e, Mode::Tail, false);
                }
                Some(_) => {
                    self.span(a, e, Mode::Tail, false);
                }
                None => {}
            }
            a = e + 1;
        }
    }

    /// Sort, drop overlaps and anything at/after `cut`, split at line ends and
    /// convert byte ranges to 1-based (line, character column, character length).
    fn finish(mut self, cut: usize) -> Vec<HighlightToken> {
        self.out.sort_by_key(|t| (t.0, t.1));
        let mut tokens = Vec::new();
        let mut last_end = 0usize;
        let mut line_starts = vec![0usize];
        line_starts.extend(self.text.match_indices('\n').map(|(k, _)| k + 1));
        for (s, e, class_name) in self.out {
            if s < last_end || s >= cut {
                continue;
            }
            let e = e.min(cut);
            last_end = e;
            let mut a = s;
            while a < e {
                let line_end = self.text[a..e].find('\n').map(|k| a + k).unwrap_or(e);
                if line_end > a {
                    let line = line_starts.partition_point(|&ls| ls <= a);
                    let ls = line_starts[line - 1];
                    let text = &self.text[a..line_end];
                    tokens.push(HighlightToken {
                        line: line as u32,
                        col: self.text[ls..a].chars().count() as u32 + 1,
                        len: text.chars().count() as u32,
                        class: class_name.to_string(),
                        text: text.to_string(),
                    });
                }
                a = line_end + 1;
            }
        }
        tokens
    }
}

fn diagnostic_error(d: &SyntaxDiagnostic) -> RivetError {
    let e = RivetError::syntax(&d.code, d.message.clone(), Some(d.span.clone()));
    match &d.help {
        Some(h) => e.with_hint(h.clone()),
        None => e,
    }
}

// vhco:usecase language.highlight_source(input: SourceFile) -> HighlightToken[] needs Parser
// vhco:label Highlight source
// vhco:about Tokenizes one .rivet source into classified HighlightTokens from the real Capy parser spans (keyword, option, type, effect, string, interpolation, number, comment, operation id, global, variable, operator) for `rivet highlight`, rivet::highlight::tokens and rivet_highlight (PROP-2026-0002 R17).
// vhco:example input={path:"app.rivet", text:"global api = \"https://api.example.com\""} => [{"line":1,"col":1,"len":6,"class":"keyword","text":"global"}, {"line":1,"col":8,"len":3,"class":"global","text":"api"}, {"line":1,"col":12,"len":1,"class":"operator","text":"="}, {"line":1,"col":14,"len":25,"class":"string","text":"\"https://api.example.com\""}]
pub fn highlight_source(
    input: &SourceFile,
    parser: &dyn Parser,
) -> (Vec<HighlightToken>, Option<RivetError>) {
    let table = match Table::load() {
        Ok(t) => t,
        Err(e) => return (Vec::new(), Some(e)),
    };
    // vhco:todo parse_spans -- parse the file once through the Parser port (the same Capy grammar `check` uses); walk every statement node, its body, `else` section and closer; each node's leading keyword, capture spans (id, var, name, kind, value, cond, iter, rest, …) and the literals between captures are lexed at their exact byte offsets, so every token's line/col/len comes from a real parser span and lies inside the source
    // vhco:step parse parser.parse -- one parse; a parser failure (internal) returns no tokens and that error
    let tree = match parser.parse(input) {
        Ok(t) => t,
        Err(e) => return (Vec::new(), Some(e)),
    };
    let mut t = Tokens {
        text: &input.text,
        table,
        globals: HashSet::new(),
        out: Vec::new(),
        covered: Vec::new(),
    };
    for n in tree.nodes.iter().filter(|n| n.func == "global") {
        if let Some(name) = n.text("rest").split(['=', ' ', '\t']).next()
            && !name.is_empty()
        {
            t.globals.insert(name.to_string());
        }
    }
    // vhco:todo classify -- classify each lexeme with editors/keywords.json (generated from rivet.capy): a statement's leading literal is keyword (declaration/control), option (opt_* lines) or effect (`file`); operation/pipeline IDs and `(ID …)` calls are operation_id; built-ins after `(` and true/false/null are keyword; and/or/not/in/as and punctuation are operator; an effect head in an assignment value (`http`) and its verb (`get`) are effect; option tails mark option words, modifiers and types; names declared by `global` are global everywhere; other names are variable; strings split into string and `${…}` interpolation; `#` comments and `else` come from a scan of the text no node covers; brackets, commas, colons and object keys are not tokens
    // vhco:step classify classify -- node walk (leading keyword, captures, glue), then the gap scan for comments and `else`
    for n in &tree.nodes {
        t.node(n);
    }
    // vhco:step recover gaps -- with diagnostics, uncovered lines before the error (the header of an unclosed block) are lexed as statement lines, so no token before the error is lost
    t.gaps(!tree.diagnostics.is_empty());
    // vhco:todo partial_on_error -- when the tree has diagnostics, the earliest one (by line, column) is the error: lines no node covers (the header of an unclosed block) are lexed as statement lines, then keep only the tokens that start before it (tokens are cut at it) and return it as syntax.* with every other diagnostic in `suppressed`, so the CLI prints the partial tokens and exits 2 instead of printing nothing
    // vhco:error syntax -- the source does not parse => syntax.* (exit 2) returns with the tokens before the error
    let mut diags: Vec<&SyntaxDiagnostic> = tree.diagnostics.iter().collect();
    diags.sort_by_key(|d| (d.span.start_line, d.span.start_col));
    let (cut, error) = match diags.split_first() {
        Some((first, rest)) => {
            let mut e = diagnostic_error(first);
            e.suppressed = rest.iter().map(|d| diagnostic_error(d)).collect();
            (
                t.offset(first.span.start_line, first.span.start_col),
                Some(e),
            )
        }
        None => (input.text.len(), None),
    };
    (t.finish(cut), error)
}

#[cfg(test)]
mod tests {
    use super::*;

    // vhco:test language.highlight_source -- the span lexer keeps dotted/index paths (`xs.0`) and floats whole, finds `${…}` interpolations inside strings and stops comments at the line end
    #[test]
    fn lexer_keeps_paths_numbers_and_interpolations() {
        let src = "r = http get \"${api}/u/${id}\" # c\nx = xs.0 + 1.5";
        let kinds: Vec<(Lex, &str)> = lex(src, 0, src.len())
            .into_iter()
            .map(|(k, a, b)| (k, &src[a..b]))
            .collect();
        assert_eq!(kinds[0], (Lex::Word, "r"));
        assert_eq!(kinds[1], (Lex::Op, "="));
        assert_eq!(kinds[4].1, "\"${api}/u/${id}\"");
        assert!(matches!(&kinds[4].0, Lex::Str(i) if i.len() == 2));
        assert_eq!(kinds[5], (Lex::Comment, "# c"));
        assert_eq!(kinds[8], (Lex::Word, "xs.0"));
        assert_eq!(kinds[10], (Lex::Number, "1.5"));
    }

    // vhco:test language.highlight_source -- the embedded editors/keywords.json loads: statement literals, classes and their R17 highlight classes
    #[test]
    fn the_embedded_table_loads() {
        let t = Table::load().unwrap();
        assert_eq!(
            t.statement.get("opt_decode").map(String::as_str),
            Some("decode")
        );
        assert!(t.is("declaration", "global"));
        assert!(t.is("effect", "http"));
        assert_eq!(t.word_class("in"), Some("operator"));
    }
}
